# Generated by Django 4.2.7 on 2023-11-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='quantity',
            new_name='quantity_of_stock',
        ),
    ]
