# Generated by Django 4.2.7 on 2023-11-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('inventory', '0002_rename_quantity_inventorymovement_quantity_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
